# This file was generated by GoReleaser. DO NOT EDIT.
cask "assertlint" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "6f40cf865d0b9941facb3cb13992f1eb2d0167a7b8fc000dd06bd158b1172b73"
      url "https://github.com/dokimasia/assert-go/releases/download/lint/v#{version}/assertlint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2ba08b1161df076e6073e2ca3c9c74f03af643d0aeab7b9930b901a87ccbda9a"
      url "https://github.com/dokimasia/assert-go/releases/download/lint/v#{version}/assertlint_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ebf05c9c3f72fef6f62de40c651875e198dfdedcd27ed3461915107586904ca4"
      url "https://github.com/dokimasia/assert-go/releases/download/lint/v#{version}/assertlint_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "190de74d503f067c7965b8a790725b59942530b6a7854eea010ef282063b99f4"
      url "https://github.com/dokimasia/assert-go/releases/download/lint/v#{version}/assertlint_#{version}_linux_amd64.tar.gz"
    end
  end

  name "assertlint"
  desc "Reports hand-written checks that an assertion of go.dokimi.dev/assert states"
  homepage "https://github.com/dokimasia/assert-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "assertlint"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/assertlint"]
    end
  end

  # No zap stanza required
end
