# This file was generated by GoReleaser. DO NOT EDIT.
cask "dokimi-lint-go" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "f02cd75a70cc6895255052be69db0bf11337dfffd57c4a30a0c325b49dce6c6e"
      url "https://github.com/dokimasia/lint-go/releases/download/v#{version}/dokimi-lint-go_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3e69a16b101e0995f6585206e3e42e3b37a9046b241ffd6224645e0939136acc"
      url "https://github.com/dokimasia/lint-go/releases/download/v#{version}/dokimi-lint-go_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "05fb43001b78a2ea2d92562259cfc8f7843a57e6276c0655398b19b0dfb4a1e2"
      url "https://github.com/dokimasia/lint-go/releases/download/v#{version}/dokimi-lint-go_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0362bfb4941c38377626f40f01abe6d8cf6879ee6226b5356b3206bd1991827d"
      url "https://github.com/dokimasia/lint-go/releases/download/v#{version}/dokimi-lint-go_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dokimi-lint-go"
  desc "Reports Go error texts without their package name and expired test skips"
  homepage "https://github.com/dokimasia/lint-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dokimi-lint-go"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dokimi-lint-go"]
    end
  end

  # No zap stanza required
end
