# This file was generated by GoReleaser. DO NOT EDIT.
cask "ergon" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "26e750e44e7ad16c26545b10c96dc3bf47340b34f5a0a46f1fa270c6810216ce"
      url "https://github.com/dokimasia/ergon/releases/download/v#{version}/ergon_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1637a83a5d59d682efac53fd9a4034532a8e23fcabd07e3070f623cd643d8007"
      url "https://github.com/dokimasia/ergon/releases/download/v#{version}/ergon_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "992b95d976171e0356a968bc0ba776d4a862f8e176c158447d7e32f6d4dec5dc"
      url "https://github.com/dokimasia/ergon/releases/download/v#{version}/ergon_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "323a1dde285a3e62ca75ed5e6cbd94e09839a473d5ff2f2c7f97d6c9de9e3671"
      url "https://github.com/dokimasia/ergon/releases/download/v#{version}/ergon_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ergon"
  desc "Sets up repositories with a managed baseline and releases their packages"
  homepage "https://github.com/dokimasia/ergon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ergon"
  bash_completion "completions/ergon.bash"
  fish_completion "completions/ergon.fish"
  zsh_completion "completions/ergon.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ergon"]
    end
  end

  # No zap stanza required
end
