# This file was generated by GoReleaser. DO NOT EDIT.
cask "ergon" do
  version "0.8.4"

  on_macos do
    on_arm do
      sha256 "2ec6f261463d7cd672e65d0ec587d6cd65460d50300b23e0b66e6e2d49e752ff"
      url "https://github.com/dokimasia/ergon/releases/download/v#{version}/ergon_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bdf492966ed6f2d1c880511637ed1abe792c9ef1f346b9e10cecd8f7269c8952"
      url "https://github.com/dokimasia/ergon/releases/download/v#{version}/ergon_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b1e34070298bb8f8c58308a89c808f878f0e23b092cfe549a62900869686d764"
      url "https://github.com/dokimasia/ergon/releases/download/v#{version}/ergon_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6264a8b68448be0df0a3e8ba40aaa0e93fb9ea7d425ac770907a261a5d6c44a7"
      url "https://github.com/dokimasia/ergon/releases/download/v#{version}/ergon_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ergon"
  desc "Sets up repositories with a managed baseline and releases their packages"
  homepage "https://github.com/dokimasia/ergon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ergon"
  bash_completion "completions/ergon.bash"
  fish_completion "completions/ergon.fish"
  zsh_completion "completions/ergon.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ergon"]
    end
  end

  # No zap stanza required
end
