# This file was generated by GoReleaser. DO NOT EDIT.
cask "ergon" do
  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "2cca046718df91823f2ef17735c66192d5f87a365b955d728b6b26c6476cf995"
      url "https://github.com/dokimasia/ergon/releases/download/v#{version}/ergon_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "30e32f6f94c746d0f296373399bb28502942e2d6355cab065b0d0bd3c5a89ee0"
      url "https://github.com/dokimasia/ergon/releases/download/v#{version}/ergon_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8e0363ccc4b7753e47feb254d71be789c11917cacda92637f4535bca79fcbc25"
      url "https://github.com/dokimasia/ergon/releases/download/v#{version}/ergon_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c46aafc5ab8b0cfc81eecd3593734a04e25d3055f2ac5da00d96c054e1cf8efc"
      url "https://github.com/dokimasia/ergon/releases/download/v#{version}/ergon_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ergon"
  desc "Sets up repositories with a managed baseline and releases their packages"
  homepage "https://github.com/dokimasia/ergon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ergon"
  bash_completion "completions/ergon.bash"
  fish_completion "completions/ergon.fish"
  zsh_completion "completions/ergon.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ergon"]
    end
  end

  # No zap stanza required
end
