# This file was generated by GoReleaser. DO NOT EDIT.
cask "techne" do
  version "0.0.2"

  on_macos do
    on_arm do
      sha256 "4cb27546e6b12346c670bb4028db6be451658fe460810109d33c1e0d4bb68e4c"
      url "https://github.com/dokimasia/techne/releases/download/v#{version}/techne_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7b939ac3e174f98914c8438df16c88cb56ea836ffc2bcfe2f7a25d9abf6cbfa6"
      url "https://github.com/dokimasia/techne/releases/download/v#{version}/techne_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9197be5927049a0ab944d2e59c41026d6365d4195da54465c32396ded1a200bf"
      url "https://github.com/dokimasia/techne/releases/download/v#{version}/techne_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c78feafb238af8e052dfd3474f9c939ecb518cbb371ce9a01db8ba5b18dccc9d"
      url "https://github.com/dokimasia/techne/releases/download/v#{version}/techne_#{version}_linux_amd64.tar.gz"
    end
  end

  name "techne"
  desc "Serves code intelligence and refactoring of ten languages to AI agents over MCP"
  homepage "https://github.com/dokimasia/techne"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "techne"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/techne"]
    end
  end

  # No zap stanza required
end
