# This file was generated by GoReleaser. DO NOT EDIT.
cask "techne" do
  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "fbd092e857c99ab2443c262a0cb5e1fad673e0e407363f69db48673c44bba350"
      url "https://github.com/dokimasia/techne/releases/download/v#{version}/techne_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "40199f1ee54eeb9542349091de8c8b1d0dca059f4c60780ab5dcc4b89d088fcb"
      url "https://github.com/dokimasia/techne/releases/download/v#{version}/techne_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0acecf0245dbc7f73f6aa722cac8df0bb9d396e5b9c9cbdc83623d943fc7c860"
      url "https://github.com/dokimasia/techne/releases/download/v#{version}/techne_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "350ae1128f9f60ca0eca536a2152368cf372725b4fddce8a91985bd3b32141a6"
      url "https://github.com/dokimasia/techne/releases/download/v#{version}/techne_#{version}_linux_amd64.tar.gz"
    end
  end

  name "techne"
  desc "Serves code intelligence and refactoring of ten languages to AI agents over MCP"
  homepage "https://github.com/dokimasia/techne"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "techne"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/techne"]
    end
  end

  # No zap stanza required
end
